export const VIDOL_THEME_APPEARANCE = 'VIDOL_THEME_APPEARANCE';
export const VIDOL_THEME_NEUTRAL_COLOR = 'VIDOL_THEME_NEUTRAL_COLOR';
export const VIDOL_THEME_PRIMARY_COLOR = 'VIDOL_THEME_PRIMARY_COLOR';

export const DEFAULT_PRIMARY_COLOR = 'blue';
